name: DeadByDaylightMC
version: 0.0.2
author: NoahNok

main: noahnok.DBDL.files.DeadByDaylight
softdepend: [Multiverse-Core]

commands:
  dbdl:
    aliases: [dbd, db, deadbydaylight]
    usage: /dbdl
  arena:
    aliases: [a, da, darena]
    usage: /arena
  join:
    aliases: [j]
    usage: /join
  leave:
    usage: /leave
  stats:
    usage: /stats